name: i_chat
description: IChat Application

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
# icons
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
# bloc: => state manager
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
# intl: => date format
  intl: ^0.17.0
# expandable text
  expandable_text: ^2.3.0
# firebase
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.3
# meta: ?
  meta: ^1.8.0
# get_it: ?
  get_it: ^7.2.0
# cached_network_image:
  cached_network_image: ^3.2.2
# flutterToast:
  fluttertoast: ^8.1.1
# image_picker:
  image_picker: ^0.8.6
# bubble:
  bubble: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
